fortran_compiler_version:  # [linux64 or aarch64 or ppc64le or osx]
  - 7                      # [linux64]
  - 7                      # [aarch64]
  - 8                      # [ppc64le]
  - 11                     # [osx]
