# The language in this case has no bearing - we are going to be making use of "conda" for a
# python distribution for the scientific python stack.
language: c

os:
  - linux
  - osx

osx_image: xcode6.4

env:
    matrix:
        - PYTHON_VERSION=3.6

    global:
        - TARGET_ARCH="x64"
        - CONDA_INSTALL_LOCN="${HOME}/miniconda"

install:
    # Install and set up miniconda.
    - if [ $TRAVIS_OS_NAME == "linux" ]; then wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; fi
    - if [ $TRAVIS_OS_NAME == "osx" ]; then wget http://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh; fi
    - bash miniconda.sh -b -p $CONDA_INSTALL_LOCN
    - export PATH=${CONDA_INSTALL_LOCN}/bin:$PATH
    - conda config --set always_yes true

    # pin conda verson to 4.3.22
    #- conda config --set auto_update_conda False
    #- echo "conda ==4.3.22" >> ${CONDA_INSTALL_LOCN}/conda-meta/pinned

    - conda install --quiet conda

    # latest conda build
    - conda install 'conda-build'

    # To ease debugging, list installed packages
    - conda info -a
    - conda list
script:
    - |
       conda build recipe;
