# The language in this case has no bearing - we are going to be making use of "conda" for a
# python distribution for the scientific python stack.
language: c

os:
  - linux
  - osx

osx_image: xcode6.4

env:
    matrix:
        - PYTHON_VERSION=3.6

    global:
        - TARGET_ARCH="x64"
        - CONDA_INSTALL_LOCN="${HOME}/miniconda"

install:
    # Install and set up miniconda.
    - if [ $TRAVIS_OS_NAME == "linux" ]; then wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; fi
    - if [ $TRAVIS_OS_NAME == "osx" ]; then wget http://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh; fi
    - bash miniconda.sh -b -p $CONDA_INSTALL_LOCN
    - export PATH=${CONDA_INSTALL_LOCN}/bin:$PATH
    - conda config --set always_yes true

    # pin conda verson to 4.3.22
    #- conda config --set auto_update_conda False
    #- echo "conda ==4.3.22" >> ${CONDA_INSTALL_LOCN}/conda-meta/pinned

    - conda install --quiet conda

    # set the ordering of additional channels
    - conda config --prepend channels defaults
    - conda config --append channels bccp
    - conda config --append channels astropy

    # Install a couple of dependencies we need for sure.
    - conda install --quiet --yes astropy anaconda-client=1.6.2 jinja2 cython pycrypto
    - conda install ruamel_yaml

    # latest conda build
    - conda install 'conda-build'

    # to get fallback openmpi/mpich2
    # trying to work around https://github.com/conda/conda-build/issues/2510
    - conda install mpi4py

    # To ease debugging, list installed packages
    - conda info -a
    - conda list
script:
    # Only upload if this is NOT a pull request.
    # Get ready to build.
    # Packages are uploaded as they are built.
    - |
       conda build recipe;
