travis:
  secure:
    BINSTAR_TOKEN: HLvg/O3y2I2hdradv2yUpVLYyt3PVkISg30vwSAujlJVgTrPNOuw295KMkjzqfUV5QPa6hgtp2bDBYnEVktnSe0sPx4jwKxzUkkDr4LfYvp6shOpeo4GedG12MvXU2ymBvZ4n2jQRQNrASt0WWdF1a654fTXH2TjQmYNamK5Fdqot/PCBfnNcoBzrWhDS5zBehrDlGICUzuvQU+GejS9gyPHCOx6PpkC3Oautx2hIYrn3ZxkIPs4wCjlR08TnQ1Ku5V+4ex6+ugDYLOaqS4kSaCVTmA/WJY0kshetjW1/7Dtkdo30XDnzR0Yvv9ZI+oJefwISC4XZvUF/5gHhYYAZCmgABxp3QTSKw1cDauetubrEXF0WLw5OGHSSN5O20yiL5j87JpD93j3iwUaIwezj+qWQb/4DKiJlLz6KH0zdrOD89Jui5pv3YZUjs0zFDkdEX86viXA8kzjtbK/rdJm9x5z9A+U0pUycfutMZUp56L8v5TOArAfumPPSfMdqgYqkMg/Iod7pnUiskwBoDzNJTevENk8PiUqGtiplbzll2AjwlvCEA+QmHwkXgct+fTfOqmFW5i74bdidqDwubb5VrWSgoWHUZINMU24sripf9Q/k3rHtGS6y9JAhFVDkPqBlBsMy7CYVyr63N871++sVUIks0HMkfEB9lPE2uEyHmM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
